openapi: 3.0.3
info: { title: MOVA Sync Proxy, version: 1.0.0 }
paths:
  /validate:
    post:
      summary: Validate a MOVA plan or route
      responses:
        '200': { description: OK }
        '422': { description: Validation failed }
